// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI_MinimalAPI.Data;

#nullable disable

namespace WebAPI_MinimalAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebAPI_MinimalAPI.Models.Shirt", b =>
                {
                    b.Property<int>("ShirtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShirtId"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Price")
                        .HasColumnType("float");

                    b.Property<int?>("Size")
                        .HasColumnType("int");

                    b.HasKey("ShirtId");

                    b.ToTable("Shirts");

                    b.HasData(
                        new
                        {
                            ShirtId = 1,
                            Brand = "V Brand",
                            Color = "Yellow",
                            Gender = "women",
                            Price = 30.0,
                            Size = 6
                        },
                        new
                        {
                            ShirtId = 2,
                            Brand = "V Brand",
                            Color = "Blue",
                            Gender = "women",
                            Price = 30.0,
                            Size = 7
                        },
                        new
                        {
                            ShirtId = 3,
                            Brand = "W Brand",
                            Color = "Purple",
                            Gender = "women",
                            Price = 30.0,
                            Size = 7
                        },
                        new
                        {
                            ShirtId = 4,
                            Brand = "W Brand",
                            Color = "Black",
                            Gender = "men",
                            Price = 30.0,
                            Size = 10
                        },
                        new
                        {
                            ShirtId = 5,
                            Brand = "Y Brand",
                            Color = "White",
                            Gender = "women",
                            Price = 10.0,
                            Size = 6
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
